### ISSUE TITLE
需求  如何启动与如何运行到swagger-ui 页面

### ISSUE THREAD

**Issue by atliwen** [gnanquanmama/tropical-fish#14]
需求  如何启动与如何运行到swagger-ui 页面

**Comment by atliwen** [comment]
http://localhost:8087/swagger-ui.html 页面打不开

**Comment by gnanquanmama** [comment]
如何启动 => 执行类 BackendApplication 的 main 方法
访问swagger-ui 页面 => http://localhost:8087/backend-api/swagger-ui.html
